# 策略参数
TREND_MA = 15
TREND_MA_MAJOR = 60
SIGNAL_THRESHOLD = 3
ATR_STOP_MULT = 2.5
TRAIL_STOP_TRIGGER = 0.10
TRAIL_STOP_ATR = 4.0
RISK_PER_TRADE = 0.02
MIN_TRADE_INTERVAL = 6
COST_REF = {"commission": 2, "slippage": 10, "multiplier": 5}
INITIAL_CAPITAL = 200000.0
SLIPPAGE_TICKS = 1